server:
  port: 10001
mybatis:
  type-aliases-package: com.alex.seckill.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: classpath:com/alex/seckill/mapper/*.xml
#druid
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/seckill?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: toor
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 2
    initialSize: 1
    maxWait: 60000
    minidle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
  redis:
#    host: 192.168.0.104
    host: 127.0.0.1
    port: 6379
    timeout: 0
    poolMaxTotal: 50
    poolMaxIdle: 10
    poolMaxWait: 3