CREATE TABLE `GOOD`
(
    `ID`          bigint(20) NOT NULL AUTO_INCREMENT COMMENT '商品ID',
    `GOOD_NAME`   VARCHAR(16)    DEFAULT NULL COMMENT '商品名称',
    `GOOD_TITLE`  VARCHAR(64)    DEFAULT NULL COMMENT '商品标题',
    `GOOD_IMAGE`  VARCHAR(64)    DEFAULT NULL COMMENT '商品的图片',
    `GOOD_DETAIL` LONGTEXT COMMENT '商品详细描述',
    `GOOD_STOCK`  INT(11)        DEFAULT '0' COMMENT '商品库存, -1表示没有限制',
    `GOOD_PRICE`  DECIMAL(10, 2) DEFAULT '0.00' COMMENT '商品价格',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET=utf8mb4;


INSERT INTO GOOD VALUES (1, 'iPhone 12', 'Apple iPhone 12 (A1865) 256GB 白色 移动联通5G手机', '/img/iphone12.png',
                         'Apple iPhone 12 (A1865) 256GB 白色 移动联通5G手机', '10000', '8999.00'),
                        (2, '华为P40', '华为P40 16GB+256GB版 月光银 移动联通5G手机', '/img/huaweip40.png',
                         '华为P40 16GB+256GB版 月光银 移动联通5G手机', '10000', '5999.00');

CREATE TABLE `SECOND_KILL_GOOD`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '秒杀记录主键',
    `GOOD_ID`          bigint(20) DEFAULT NULL  COMMENT '商品ID',
    `PRICE`  DECIMAL(10, 2) DEFAULT '0.00' COMMENT '秒杀价格',
    `STOCK_COUNT`   INT(11)        DEFAULT '0' COMMENT '库存数量',
    `START_DATE` DATETIME DEFAULT NULL COMMENT '商品秒杀开始时间',
    `END_DATE` DATETIME DEFAULT  NULL COMMENT '商品秒杀结束时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET=utf8mb4;

INSERT INTO SECOND_KILL_GOOD VALUES (1,1,'100.00', 10, '2021-04-28 23:00:00', '2021-09-25 00:00:00'),
                                    (2,2,'0.01', 4, '2020-09-24 23:00:00', '2020-09-29 00:00:00');


CREATE TABLE `ORDER_INFO`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '秒杀订单主键',
    `USER_ID` bigint(20) DEFAULT NULL  COMMENT '用户ID',
    `GOOD_ID` bigint(20) DEFAULT NULL  COMMENT '商品ID',
    `DELIVERY_ADDRESS_ID` BIGINT(20) DEFAULT NULL COMMENT '收货地址ID',
    `GOOD_NAME`   VARCHAR(16)    DEFAULT NULL COMMENT '商品名称',
    `GOOD_COUNT`   INT(11)    DEFAULT '0' COMMENT '商品数量',
    `GOOD_PRICE`  DECIMAL(10, 2) DEFAULT '0.00' COMMENT '商品单价',
    `ORDER_SOURCE`   TINYINT(4)  DEFAULT '0' COMMENT '1-pc 2-android 3-ios',
    `STATUS` TINYINT(4) DEFAULT '0' COMMENT '订单状态 0-新建未支付 1-已支付 2-已发货 3-已收货 4-已退款 5-已完成',
    `CREATE_DATE` DATETIME DEFAULT NULL COMMENT '订单创建时间',
    `PAY_DATE` DATETIME DEFAULT  NULL COMMENT  '支付时间',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SECOND_KILL_ORDER`
(
    `ID` BIGINT(20) NOT NULL AUTO_INCREMENT COMMENT '秒杀记录主键',
    `USER_ID` BIGINT(20) DEFAULT NULL COMMENT '商户ID',
    `ORDER_ID` BIGINT(20) DEFAULT NULL  COMMENT '订单ID',
    `GOOD_ID` bigint(20) DEFAULT NULL  COMMENT '商品ID',
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB AUTO_INCREMENT = 3 DEFAULT CHARSET=utf8mb4;

CREATE TABLE `SECOND_KILL_USER`
(
    `ID` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '秒杀用户主键',
    `USER_ID` bigint(20) DEFAULT  NULL COMMENT '用户ID',
    `ORDER_ID` bigint(20) DEFAULT NULL  COMMENT '秒杀订单主键',
    `GOODS_ID` bigint(20) DEFAULT NULL  COMMENT '商品ID',
    PRIMARY KEY (`ID`)
)ENGINE=InnoDB AUTO_INCREMENT = 3 DEFAULT  CHARSET=utf8mb4;